### ISSUE TITLE
ActorPictures.js - Plugin Parameter Typo

### ISSUE THREAD

**Issue by EliaquimNascimento** [nz-prism/RPG-Maker-MZ#2]
Hi there.
I think there is a typo on the plugin parameters of ActorPictures.js, regarding the English section.
On line 214, the struct is:

`/*~struct~animation:ja`

When it is suppose to be without the **"ja"**

`/*~struct~animation:`

**Comment by nz-prism** [comment]
Hi EliaquimNascimiento,

Thank you so much for the information!
I've corrected it by updating the plugin to **1.3.4**.

Please check it out!

Thanks,
nz_prism
