### ISSUE TITLE
[BUG] PictureMessage.js. "Erase Picture" command doesn't return x or y to default state.

### ISSUE THREAD

**Issue by RyanBram** [nz-prism/RPG-Maker-MZ#4]
親愛なる、開発者の皆様へ。

会話イベントを起動する際、Erase Pictureコマンドに期待されるのは、ピクチャー全体を消去する以外に、ピクチャーの設定を全て元に戻すことです。しかし、現状ではErase Picture機能はピクチャーの表示を消すだけなので、次のイベントを表示したいときに、イージング効果でアクターの位置がさらにずれてしまう可能性があるようです。

以下はそのスクリーンショットです。

https://user-images.githubusercontent.com/4508389/215554750-19af6ced-cbd1-4ac0-af34-1058de22d7f4.mp4

Move Pictureコマンドでも同じことが起こります。Move Pictureコマンドの会話では、アクターピクチャーが変更されても、置き換えられたアクターは、初期設定位置に戻るのではなく、前のアクターと同じx、y位置を占めます。つまり、アクターを変更するたびに、手動で位置を戻す必要があり、イベントページで必要なコマンドが長くなりすぎてしまいます。

今回のレポートの補足として、前回の1437行目をこのように置き換えてみました。
```
const PICTURE_COORDINATES = [
{x: Number(pluginParams.leftPictureX),   y: Number(pluginParams.leftPictureY)},
{x: Number(pluginParams.centerPictureX), y: Number(pluginParams.centerPictureY)},
{x: Number(pluginParams.rightPictureX),  y: Number(pluginParams.rightPictureY)}
];
```

このようになるように。
```
const PICTURE_COORDINATES = [
{x: Number(pluginParams.leftPictureX),   y: Number (Graphics.height - pluginParams.leftPictureY)},
{x: Graphics.width / 2 + Number(pluginParams.centerPictureX), y: Number (Graphics.height - pluginParams.centerPictureY)},
{x: Graphics.width - Number(pluginParams.rightPictureX),  y: Number(Graphics.height - pluginParams.rightPictureY)}
];
```

xとyの位置が常に画面幅に対して相対的になるようにやってみました。しかし、超初心者プログラマーの私には、なぜGraphics.widthとGraphics.heightのコードが正しく読み込まれないのか理解できません。

ありがとうございました。
---
Dear, Developer,

When activating the conversation event, what is expected with the Erase Picture command besides erasing the entire picture is to restore all the picture settings back to the original. However, it seems that the Erase Picture function currently only erases the picture display, so that when you want to display the next event, the actor's position has the potential to be further displaced due to the easing effect.

Here is the screen capture:
https://user-images.githubusercontent.com/4508389/215554750-19af6ced-cbd1-4ac0-af34-1058de22d7f4.mp4

The same thing happens with the Move Picture command. If in a Move Picture command conversation, then even if the actor picture has changed, the replacement actor will occupy the same x and y position as the previous actor, instead of returning to the initial setting position which means that for each actor change, it is necessary to return the position manually which causes the command needed in the event page to be too long.

As an addition to this report, I tried replacing line 1437 from the previous one like this:
```
const PICTURE_COORDINATES = [
{x: Number(pluginParams.leftPictureX),   y: Number(pluginParams.leftPictureY)},
{x: Number(pluginParams.centerPictureX), y: Number(pluginParams.centerPictureY)},
{x: Number(pluginParams.rightPictureX),  y: Number(pluginParams.rightPictureY)}
];
```

To be like this:
```
const PICTURE_COORDINATES = [
{x: Number(pluginParams.leftPictureX),   y: Number (Graphics.height - pluginParams.leftPictureY)},
{x: Graphics.width / 2 + Number(pluginParams.centerPictureX), y: Number (Graphics.height - pluginParams.centerPictureY)},
{x: Graphics.width - Number(pluginParams.rightPictureX),  y: Number(Graphics.height - pluginParams.rightPictureY)}
];
```

I did this so that the x and y positions are always relative to the screen width and height. But as a very beginner programmer, I don't understand why the Graphics.width and Graphics.height codes don't read properly. 

Thank you very much.

**Comment by nz-prism** [comment]
Hi Ryan Bram,

Thank you for the inquiry.
Actually, this is a designed behavior. The pictures invoked from this plugin keep all the settings including X/Y before they are erased.
To reset the settings, use "Initialize Picture" plugin command.

Plus, if you face this issue with a plugin because of a change you made to it, make sure whether the same issue happens with the original plugin.

If you have any questions, feel free to ask me!

Thanks,
んーぞー@nz_prism
